/**
 * The Raybot agent model.
 *
 * This describes a Copilot Studio agent as it exists in the next-generation
 * runtime (codename Coral): an identity minted on first save, a build-time
 * configuration on the Build tab, four tabs of settings, and a set of publish
 * targets. Every field name here is derived from observed UI state and observed
 * request or response payloads, not from a published API contract.
 */

import type { ConfidenceLevel, Evidenced, Guid, IsoInstant } from './common.js';

/* ------------------------------------------------------------------ identity */

/**
 * The immutable half of an agent.
 *
 * The agent id is minted by the platform on the first successful save, not at
 * the moment the create dialog is submitted. Publish, Share, and Evaluate stay
 * disabled until that first save completes, because each of them needs the id.
 *
 * `schemaName` is generated by the platform with a random suffix and is
 * read-only from the moment it is assigned. It is the Dataverse logical name
 * used in `bots(...)` lookups.
 */
export interface AgentIdentity {
  /** Platform-minted agent id, created on first save. */
  agentId: Guid;
  /** Display name shown in the designer and in channels. */
  displayName: string;
  /** Platform-generated Dataverse schema name. Read-only after first save. */
  schemaName: string;
  /** Power Platform environment id, `Default-<tenantGuid>` for default envs. */
  environmentId: string;
  /** Human-readable environment name. */
  environmentName?: string;
  /** Description surfaced in the agent list and in channel metadata. */
  description?: string;
}

/* --------------------------------------------------------------------- icon */

/**
 * Agent icon constraints, confirmed by rejection and acceptance during Phase 1.
 *
 * The upload control accepts PNG only and enforces a hard 100 KB ceiling. A
 * 512 px render of the Raybot logo was 195.8 KB and was rejected outright; the
 * 256 px render was 53.8 KB and was accepted. The ceiling is on encoded file
 * size, not on pixel dimensions, so the practical rule is to downscale until
 * the encoded PNG clears 100 KB.
 */
export interface AgentIcon {
  /** Only `image/png` was accepted by the upload control. */
  contentType: 'image/png';
  /** Encoded size in bytes. Must be under {@link ICON_MAX_BYTES}. */
  sizeBytes: number;
  /** Square edge length in pixels. */
  edgePixels: number;
  fileName: string;
}

/** Hard ceiling enforced by the icon upload control: 100 KB. */
export const ICON_MAX_BYTES = 100 * 1024;

/** Icon sizes observed during Phase 1, with their outcome. */
export const ICON_SIZE_OBSERVATIONS = [
  { edgePixels: 512, sizeBytes: 200_499, accepted: false },
  { edgePixels: 256, sizeBytes: 55_091, accepted: true },
] as const;

/** Returns true when an icon candidate satisfies the observed constraints. */
export function isIconAcceptable(icon: Pick<AgentIcon, 'contentType' | 'sizeBytes'>): boolean {
  return icon.contentType === 'image/png' && icon.sizeBytes <= ICON_MAX_BYTES;
}

/* ---------------------------------------------------------------- knowledge */

/**
 * A knowledge source attached to the agent.
 *
 * Raybot uses a single public website source pointed at the Ray documentation.
 * The card types offered by the add-knowledge flow are enumerated here because
 * the set is a closed list in the UI.
 */
export type KnowledgeSourceKind =
  | 'publicWebsite'
  | 'sharePoint'
  | 'dataverse'
  | 'file'
  | 'enterpriseData'
  | 'microsoftIQ';

export interface KnowledgeSource extends Evidenced {
  kind: KnowledgeSourceKind;
  /** Display name shown on the knowledge card. */
  name: string;
  /** Root URL for `publicWebsite` and `sharePoint` sources. */
  url?: string;
  /** Description passed to the orchestrator to decide when to search. */
  description?: string;
}

/* -------------------------------------------------------------------- tools */

/**
 * The four tabs offered by the add-tool flyout, plus the custom entry point.
 *
 * `custom` corresponds to the explicit "Add" affordance that lets a maker
 * register a tool that is not present in any of the four catalogs.
 */
export type ToolCatalog =
  | 'featured'
  | 'mcp'
  | 'connectors'
  | 'workflows'
  | 'custom';

export interface AgentTool extends Evidenced {
  catalog: ToolCatalog;
  name: string;
  /** Description the orchestrator reads when deciding to invoke the tool. */
  description?: string;
  /** Present for MCP-sourced tools. */
  mcpServer?: string;
  /** Present for connector-sourced tools. */
  connectorId?: string;
}

/* ------------------------------------------------------------------- skills */

/**
 * A skill authored in the skill editor.
 *
 * The editor offers two entry modes: start from a blank skill, or start from a
 * generated draft. Raybot's `ray-cluster-troubleshooter` was authored blank.
 */
export type SkillEntryMode = 'blank' | 'generated';

export interface AgentSkill extends Evidenced {
  name: string;
  entryMode: SkillEntryMode;
  /** Short summary shown on the skill card. Capped at 1024 characters. */
  description?: string;
  /** Natural-language instructions that define the skill's behaviour. */
  instructions?: string;
}

/** `maxLength` observed on `skill-name-input`. */
export const SKILL_NAME_MAX_LENGTH = 64;

/** `maxLength` observed on `skill-description-input`. */
export const SKILL_DESCRIPTION_MAX_LENGTH = 1024;

/* ---------------------------------------------------------- connected agents */

/**
 * A connected (child) agent reference.
 *
 * The connect flow refuses drafts: only published agents can be connected. This
 * is the single most common cause of an empty connected-agent picker.
 */
export interface ConnectedAgent extends Evidenced {
  agentId: Guid;
  displayName: string;
  /** Always true in practice, because the picker filters drafts out. */
  isPublished: boolean;
}

/* -------------------------------------------------------------- Microsoft IQ */

/**
 * A Microsoft IQ (Foundry IQ) knowledge base binding.
 *
 * The binding points at an Azure AI Search knowledge base created through the
 * `2025-11-01-preview` Search REST surface. The tier constraint is the critical
 * one: knowledge bases hosted on a Free-tier search service never appear in the
 * Copilot Studio picker, regardless of whether they answer correctly over REST.
 */
export interface MicrosoftIQBinding extends Evidenced {
  /** Knowledge base name, for example `raybot-kb`. */
  knowledgeBase: string;
  /** Azure AI Search service short name. */
  searchService: string;
  /** Azure region of the search service. */
  region: string;
  /** Search service SKU. Basic or higher is required for the picker. */
  sku: 'free' | 'basic' | 'standard' | 'standard2' | 'standard3';
  /** Names of the knowledge sources bound into the knowledge base. */
  knowledgeSources: string[];
  /** Search REST api-version used. Only this version exposes /knowledgeBases. */
  apiVersion: string;
  outputMode?: 'answerSynthesis' | 'extractiveData';
  retrievalReasoningEffort?: 'low' | 'medium' | 'high';
  /** Azure OpenAI deployment backing answer synthesis. */
  synthesisModel?: string;
}

/** Minimum Azure AI Search SKU whose knowledge bases appear in the picker. */
export const MICROSOFT_IQ_MIN_SKU = 'basic';

/** The only Search REST api-version that exposes the knowledgeBases surface. */
export const SEARCH_API_VERSION = '2025-11-01-preview';

/* ------------------------------------------------------------------- memory */

/** Conversation memory toggle state on the Build tab right rail. */
export interface AgentMemory {
  enabled: boolean;
}

/* ------------------------------------------------------- build configuration */

/**
 * Everything configured on the Build tab and its right rail.
 */
export interface AgentConfiguration {
  /** Model selected for the agent, for example `Claude Sonnet 4.6`. */
  model: string;
  /** System instructions authored in the instructions editor. */
  instructions?: string;
  icon?: AgentIcon;
  knowledge: KnowledgeSource[];
  tools: AgentTool[];
  skills: AgentSkill[];
  connectedAgents: ConnectedAgent[];
  microsoftIQ: MicrosoftIQBinding[];
  memory: AgentMemory;
}

/* ----------------------------------------------------------------- settings */

/** Content moderation levels, ordered from least to most restrictive. */
export type ModerationLevel =
  | 'Minimum'
  | 'Low'
  | 'Medium'
  | 'High'
  | 'Maximum';

export const MODERATION_LEVELS: readonly ModerationLevel[] = [
  'Minimum',
  'Low',
  'Medium',
  'High',
  'Maximum',
] as const;

/** End-user authentication mode for the agent. */
export type AuthenticationMode =
  | 'NoAuthentication'
  | 'AuthenticateWithMicrosoft'
  | 'Manual';

/** Settings tab: Details. Identity fields are read-only after first save. */
export interface DetailsSettings {
  displayName: string;
  description?: string;
  /** Read-only after the first save. */
  schemaName: string;
  /** Read-only after the first save. */
  agentId: Guid;
}

/** Settings tab: Security. */
export interface SecuritySettings {
  authentication: AuthenticationMode;
  /**
   * Enabling this while relying on the Demo or Preview surfaces locks the
   * maker out of their own agent preview. Leave it off until a real channel is
   * carrying traffic.
   */
  requireSecuredAccess: boolean;
}

/** Settings tab: Generative AI. */
export interface GenerativeAiSettings {
  moderationLevel: ModerationLevel;
  /** Whether end users can leave thumbs-up or thumbs-down feedback. */
  userFeedbackEnabled: boolean;
}

/** Settings tab: Conversation start. */
export interface ConversationStartSettings {
  /** Greeting message. Empty for Raybot. */
  greeting?: string;
  /** Suggested prompt chips. Empty for Raybot. */
  suggestedPrompts: string[];
}

export interface AgentSettings {
  details: DetailsSettings;
  security: SecuritySettings;
  generativeAi: GenerativeAiSettings;
  conversationStart: ConversationStartSettings;
}

/* ---------------------------------------------------------------- publishing */

/** Channels observed in the Coral publish surface. */
export type PublishChannelKind =
  | 'demo'
  | 'teams'
  | 'm365Copilot'
  | 'website'
  | 'customWebsite'
  | 'slack'
  | 'directLine';

export interface PublishChannel extends Evidenced {
  kind: PublishChannelKind;
  /** Whether the channel toggle reports itself as enabled in the UI. */
  uiReportsEnabled: boolean;
  /** Whether traffic was actually observed reaching the agent. */
  verifiedReachable: boolean;
  blockedReason?: string;
}

/**
 * A publish operation.
 *
 * Coral publishes inline with no confirmation dialog: the command bar posts to
 * a publish operations endpoint and then long-polls the returned operation id
 * until it terminates.
 */
export interface PublishOperation extends Evidenced {
  operationId?: string;
  startedAt?: IsoInstant;
  completedAt?: IsoInstant;
  succeeded: boolean;
}

/* ------------------------------------------------------------------- agent */

/** The complete agent aggregate. */
export interface RaybotAgent {
  identity: AgentIdentity;
  configuration: AgentConfiguration;
  settings: AgentSettings;
  channels: PublishChannel[];
  /** Confidence of the aggregate as a whole. */
  confidence: ConfidenceLevel;
}
