/**
 * Emits JSON Schema (draft 2020-12) for every top-level exported interface in
 * `@raybot/object-model`.
 *
 * One file per interface, written to `schemas/`, plus a mirror under the site's
 * `static/schemas/` so the schemas are addressable by URL once deployed.
 *
 * Run: npm run schemas
 */
import { createGenerator } from 'ts-json-schema-generator';
import { mkdirSync, writeFileSync, rmSync, readdirSync, copyFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, '..');
const REPO = resolve(PKG, '..', '..');
const OUT = join(PKG, 'schemas');
const STATIC_OUT = join(REPO, 'static', 'schemas');

const BASE_URI = 'https://dayour.github.io/raybot/schemas';

/**
 * Top-level interfaces published as standalone contracts.
 *
 * Deliberately excludes the bare union aliases (`ConfidenceLevel`,
 * `OutcomeStatus`, and friends): they carry no object shape of their own and
 * are inlined by reference into every schema that uses them.
 */
const TYPES = [
  'Evidenced',
  'AgentIdentity',
  'AgentIcon',
  'KnowledgeSource',
  'AgentTool',
  'AgentSkill',
  'ConnectedAgent',
  'MicrosoftIQBinding',
  'AgentMemory',
  'AgentConfiguration',
  'DetailsSettings',
  'SecuritySettings',
  'GenerativeAiSettings',
  'ConversationStartSettings',
  'AgentSettings',
  'PublishChannel',
  'PublishOperation',
  'RaybotAgent',
  'CoralSemanticId',
  'ApiSemanticId',
  'CoralSurface',
  'CoralElement',
  'CoralTestId',
  'ApiHost',
  'ApiEndpoint',
  'AuditTotals',
  'WorkflowTriggerDefinition',
  'WorkflowNodeDefinition',
  'WorkflowNode',
  'Workflow',
  'StepTarget',
  'RunbookStep',
  'RunbookPhase',
  'Runbook',
  'EvalTestCase',
  'EvalTestSet',
  'EvalCaseResult',
  'EvalRun',
  'SessionRecord',
  'SessionCommand',
  'ScreenshotCapture',
  'ShowcaseConnector',
  'ShowcaseWorkflow',
  'IncidentTriageBuildStep',
  'DesignerPitfall',
  'AutomationCandidate',
];

const generator = createGenerator({
  path: join(PKG, 'src', 'index.ts'),
  tsconfig: join(PKG, 'tsconfig.json'),
  type: '*',
  expose: 'export',
  topRef: true,
  jsDoc: 'extended',
  additionalProperties: true,
  sortProps: true,
  skipTypeCheck: false,
});

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

let emitted = 0;
const index = [];

for (const type of TYPES) {
  let schema;
  try {
    schema = generator.createSchema(type);
  } catch (err) {
    console.error(`FAILED ${type}: ${err.message}`);
    process.exitCode = 1;
    continue;
  }

  const file = `${type}.schema.json`;
  const final = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: `${BASE_URI}/${file}`,
    $ref: schema.$ref,
    definitions: schema.definitions,
  };

  writeFileSync(join(OUT, file), `${JSON.stringify(final, null, 2)}\n`, 'utf8');
  index.push({ type, file, $id: final.$id });
  emitted += 1;
}

writeFileSync(
  join(OUT, 'index.json'),
  `${JSON.stringify(
    {
      $comment:
        'Generated by scripts/emit-schemas.mjs. Do not edit by hand; run npm run schemas.',
      package: '@raybot/object-model',
      dialect: 'https://json-schema.org/draft/2020-12/schema',
      baseUri: BASE_URI,
      count: index.length,
      schemas: index,
    },
    null,
    2,
  )}\n`,
  'utf8',
);

rmSync(STATIC_OUT, { recursive: true, force: true });
mkdirSync(STATIC_OUT, { recursive: true });
for (const name of readdirSync(OUT)) {
  copyFileSync(join(OUT, name), join(STATIC_OUT, name));
}

console.log(`Emitted ${emitted} schemas to schemas/ and mirrored to static/schemas/`);
